### ISSUE TITLE
How to watch for changes to signal without using signal value

### ISSUE THREAD

**Issue by felixranesberger** [maverick-js/signals#36]
Hi, thanks for your library! 
I've used Vue in the past and was wondering, how to implement a function callback, when a signal changes, without directly using the value inside the effect. 

In Vue I would implement it like this:
```ts
watch(myReactiveVariable, () => {
     myCallbackFunction();
})
```

I tried using `effect` but this requires the variable to be used inside the callback function, which I don't need. 
Calling a `console.log` inside the callback function for `effect` also seems unnecessary. 

```ts
// Effect - this will run whenever `$y` is updated.
const stop = effect(() => {
  console.log($y());
  myCallbackFunction();
});
```

How would you implement this?
Thanks already for any answer :)

**Comment by mihar-22** [comment]
I don't understand, if a signal is used anywhere inside a sync callback it will be included in the effect. You don't need to call a signal directly inside the effect. If the effect is not updating because of a signal inside `myCallbackFunction` then it might be because that signal is called after the effect callback has ran.

**Comment by felixranesberger** [comment]
Sorry for the late response! I didn't know that effect also works on functions that are called from the effect callback function. Thanks for the explanation, worked like a charm!
